apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: zadanie-2
spec:
  selector:
    app: php-apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP