apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: zadanie-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: php:7.4-apache
        ports:
        - containerPort: 80
        volumeMounts:
        - name: apache-content
          mountPath: /var/www/html
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: php-apache-secret
              key: DB_PASSWORD
        - name: MYSQL_SERVICE_HOST
          value: "mysql" 
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: apache-content
        configMap:
          name: apache-content
